// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchPlaylist(arg1) {
  return window['go']['main']['App']['FetchPlaylist'](arg1);
}
